### ISSUE TITLE
URGENT: You've been hacked

### ISSUE THREAD

**Issue by JayDDee** [mhahsler/arulesNBMiner#1]
Your Wiki has been hacked and used to to spread malware. Phishing links are posted to various forums pointing to this
wiki which then links to malware. Using your repo as an intermediary gives a sense of legitimacy to the scam.

I have reported the offending github user but that only will only prevent further damage by that user. The existing damage
needs to be cleaned up ASAP. You should also review your security to ensure you don't get hacked again.

The hacker is: https://github.com/Cberry

Your hacked Wiki: https://github.com/mhahsler/arulesNBMiner/wiki

**Comment by mhahsler** [comment]
Thank you for finding this! I have deactivated the Wiki and related the links.

Regards,
-Michael
